site_name: docs.repo.trade
site_url: https://docs.repo.trade
theme:
  name: material
  palette:
    primary: yellow
  navigation_depth: 2
  font:
    text: Roboto Mono
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - ğŸ  Home: index.md
  - ğŸ“„ Whitepaper: whitepaper.md
  - ğŸ“š Short Story: short-story.md
  - ğŸ’¡ Concepts:
      - concepts/namespaces.md
      - concepts/repos.md
      - concepts/rewards.md
      - concepts/swaps.md
  # - FAQs: faqs.md
  - ğŸ“– Glossary: glossary.md
  - â“ Support: support.md
